services:
  expense-tracker:
    build: .
    ports:
      - "8051:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=false
      - DATABASE_PATH=/app/data/db.sqlite3
    networks:
      - shared_net

networks:
  shared_net:
    external: true
