const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async()=>{
 const base = process.env.NUMI_TEST_URL || 'http://127.0.0.1:8765';
 assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname),'Run this data-creating test only on a local preview');
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || undefined});
 const context=await browser.newContext({viewport:{width:1200,height:950}});
 const page=await context.newPage(), errors=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('dialog',d=>d.accept());
 await page.route('**/api/geo/currency/',r=>r.fulfill({json:{currency:'SGD'}}));
 await page.route('**/api/rates/',r=>r.fulfill({json:{rates:{usd:1,sgd:1.3,cny:7}}}));
 await page.route('https://cdn.jsdelivr.net/**',r=>r.abort());
 await page.goto(base+'/expenses/travel/');
 await page.getByRole('button',{name:'+ Add Trip'}).click();
 await page.locator('#tripDest').fill('Shanghai planner QA');
 await page.locator('#tripStart').fill('2026-10-01');await page.locator('#tripEnd').fill('2026-10-03');
 await page.locator('#addTripForm button[type=submit]').click();
 await page.getByRole('tab',{name:'Places',exact:true}).click();
 await page.getByRole('button',{name:'+ Add place'}).click();
 let dialog=page.locator('dialog');
 await dialog.locator('[name=title]').fill('Tea & Coffee');await dialog.locator('[name=category]').selectOption('Restaurant');
 await dialog.locator('[name=address]').fill('南京西路 1 号');
 await dialog.locator('.share-text').fill('菜单 https://example.com/menu。 地图 https://j.map.baidu.com/abc');
 await page.getByRole('button',{name:'Add detected links'}).click();
 await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByText('Plan synced',{exact:false}).waitFor();
 await page.locator('.plan-panel summary').filter({hasText:'Tea & Coffee'}).click();
 assert.match(await page.getByRole('link',{name:'Baidu Maps · Map',exact:true}).getAttribute('href'),/api.map.baidu.com/);
 await page.getByRole('button',{name:'Add to itinerary'}).click();
 await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByRole('tab',{name:'Itinerary',exact:true}).click();
 await page.getByRole('button',{name:'+ Add activity'}).click();await dialog.locator('[name=title]').fill('Shopping');
 await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByText('Plan synced',{exact:false}).waitFor();
 await page.locator('.plan-panel summary').filter({hasText:'Shopping'}).click();
 await page.getByRole('button',{name:'↑ Move up'}).last().click();
 await page.getByText('Plan synced',{exact:false}).waitFor();
 assert.match(await page.locator('.plan-panel summary').first().textContent(),/^Shopping/);
 await page.locator('.plan-panel summary').first().click();
 await page.locator('.plan-panel details').first().getByRole('button',{name:'Edit',exact:true}).click();
 await dialog.locator('[name=date]').fill('2026-10-02');await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByRole('tab',{name:'Bookings',exact:true}).click();await page.getByRole('button',{name:'+ Add booking'}).click();
 await dialog.locator('[name=title]').fill('Riverside Hotel');await dialog.locator('[name=date]').fill('2026-10-01');await dialog.locator('[name=endDate]').fill('2026-10-03');
 await dialog.locator('[name=confirmation]').fill('WEB-123');await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByRole('tab',{name:'Preparation',exact:true}).click();await page.getByRole('button',{name:'+ Add checklist item'}).click();
 await dialog.locator('[name=title]').fill('Pack charger');await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByText('Plan synced',{exact:false}).waitFor();await page.locator('.plan-panel summary').first().click();await page.getByRole('button',{name:'Complete',exact:true}).click();
 await page.getByText('Plan synced',{exact:false}).waitFor();
 await context.setOffline(true);
 await page.getByRole('tab',{name:'Places',exact:true}).click();await page.getByRole('button',{name:'+ Add place'}).click();
 await dialog.locator('[name=title]').fill('Offline shopping mall');await dialog.locator('[name=category]').selectOption('Shopping');await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByText('Could not sync.',{exact:false}).waitFor();
 await context.setOffline(false);await page.getByRole('button',{name:'Sync now'}).click();await page.getByText('Plan synced',{exact:false}).waitFor();
 await page.getByRole('tab',{name:'Expenses',exact:true}).click();assert.equal(await page.getByText('Add Expense',{exact:true}).count(),1);
 await page.getByRole('tab',{name:'Overview',exact:true}).click();assert.equal(await page.getByText('Accommodation gaps',{exact:true}).count(),0);
 await page.screenshot({path:'/tmp/numi-web-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('tab',{name:'Places',exact:true}).click();
 await page.screenshot({path:'/tmp/numi-web-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 const planKey=await page.evaluate(()=>Object.keys(localStorage).find(k=>k.startsWith('numi.travel.plan.v1.')));
 const tripId=planKey.split('.').at(-1);
 // A second device changes the document while this browser has pending edits.
 await context.setOffline(true);
 await page.getByRole('button',{name:'+ Add place'}).click();
 await dialog.locator('[name=title]').fill('Conflict-safe cafe');
 await page.getByRole('button',{name:'Save item',exact:true}).click();
 await page.getByText('Could not sync.',{exact:false}).waitFor();
 const remote=await (await context.request.get(base+`/expenses/api/travel/trips/${tripId}/plan/`)).json();
 const response=await context.request.put(base+`/expenses/api/travel/trips/${tripId}/plan/`,{data:{content:{items:[]},revision:remote.revision,mutation_id:'browser-test-other-device'}});
 assert.equal(response.status(),200);
 await context.setOffline(false);
 await page.getByRole('button',{name:'Sync now'}).click();
 await page.getByRole('button',{name:'Keep this browser'}).waitFor();
 await page.getByRole('button',{name:'Keep this browser'}).click();
 await page.getByText('Plan synced',{exact:false}).waitFor();
 await page.reload();
 await page.locator(`.trip-header[onclick="toggleTrip(${tripId})"]`).click();
 await page.getByRole('tab',{name:'Places',exact:true}).click();
 await page.locator('summary').filter({hasText:'Conflict-safe cafe'}).waitFor();
 assert.deepEqual(errors,[]);console.log('Web desktop/mobile planning flow and offline retry passed');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
