# Generated by Django 6.0.2 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_trip_travelexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_cny',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_hkd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_sgd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='amount_cny',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='amount_hkd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='amount_sgd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='travelexpense',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate_cny',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate_hkd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rate_sgd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='travelexpense',
            name='rate_to_usd',
            field=models.FloatField(default=0),
        ),
    ]
