# Generated by Django 6.0.2 on 2026-03-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_amount_cny_expense_amount_hkd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='rate_cny',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rate_hkd',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rate_sgd',
        ),
        migrations.RemoveField(
            model_name='travelexpense',
            name='rate_to_usd',
        ),
    ]
