# Generated by Django 6.0.2 on 2026-03-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('credit', 'Credit Card'), ('stored', 'Stored Value Card'), ('investment', 'Investment')], max_length=20)),
                ('currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD'), ('SGD', 'SGD'), ('JPY', 'JPY')], max_length=3)),
                ('balance', models.FloatField(default=0)),
                ('is_liability', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('change', models.FloatField(default=0)),
                ('snapshot_date', models.DateField()),
                ('rate_cny', models.FloatField()),
                ('rate_hkd', models.FloatField()),
                ('rate_sgd', models.FloatField()),
                ('rate_jpy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assets.account')),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
    ]
