# Generated by Django 6.0.2 on 2026-03-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_liability',
        ),
        migrations.AddField(
            model_name='account',
            name='include_in_total',
            field=models.BooleanField(default=True),
        ),
    ]
