# Generated by Django 6.0.2 on 2026-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_account_options_remove_account_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesnapshot',
            name='amount_cny',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='amount_hkd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='amount_sgd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='balancesnapshot',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='rate_cny',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='rate_hkd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='rate_jpy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='balancesnapshot',
            name='rate_sgd',
            field=models.FloatField(default=0),
        ),
    ]
