# Generated by Django 6.0.2 on 2026-03-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_balancesnapshot_amount_cny_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='rate_cny',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='rate_hkd',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='rate_jpy',
        ),
        migrations.RemoveField(
            model_name='balancesnapshot',
            name='rate_sgd',
        ),
    ]
