# Generated by Django 6.0.2 on 2026-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_balancesnapshot_rate_cny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_auth',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='api_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='api_value_path',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
