# Generated by Django 6.0.2 on 2026-03-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('cny', models.FloatField()),
                ('hkd', models.FloatField()),
                ('sgd', models.FloatField()),
            ],
            options={
                'ordering': ['-rate_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('CNY', 'CNY'), ('HKD', 'HKD'), ('USD', 'USD'), ('SGD', 'SGD')], max_length=3)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('rate_cny', models.FloatField()),
                ('rate_hkd', models.FloatField()),
                ('rate_sgd', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
