# Generated by Django 6.0.2 on 2026-09-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expense_rate_cny_remove_expense_rate_hkd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('mutation_id', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='expenses.trip')),
            ],
        ),
    ]
