# Generated by Django 6.0.2 on 2026-09-22 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_backfill_travel_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('person_id', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='expenses.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('actor', models.CharField(default='Owner', max_length=100)),
                ('mutation_id', models.CharField(blank=True, max_length=64)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_changes', to='expenses.trip')),
            ],
            options={
                'ordering': ['-revision'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'revision'), name='unique_trip_plan_revision')],
            },
        ),
    ]
