# Generated by Django 6.0.2 on 2026-09-22 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_tripinvite_tripplanchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expenses.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trip', 'sha256'), name='unique_trip_document_hash')],
            },
        ),
    ]
